// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAugmentByName(arg1) {
  return window['go']['main']['App']['GetAugmentByName'](arg1);
}

export function GetAvailableAugments(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAvailableAugments'](arg1, arg2, arg3);
}

export function GetAvailableFiligrees(arg1) {
  return window['go']['main']['App']['GetAvailableFiligrees'](arg1);
}

export function GetAvailableItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAvailableItems'](arg1, arg2, arg3);
}

export function GetFiligreeByName(arg1) {
  return window['go']['main']['App']['GetFiligreeByName'](arg1);
}

export function GetItemDetails(arg1) {
  return window['go']['main']['App']['GetItemDetails'](arg1);
}

export function GetSetBonus(arg1) {
  return window['go']['main']['App']['GetSetBonus'](arg1);
}

export function GetSlotAlternatives(arg1) {
  return window['go']['main']['App']['GetSlotAlternatives'](arg1);
}

export function GetStatSets() {
  return window['go']['main']['App']['GetStatSets']();
}

export function GetSystemLogs() {
  return window['go']['main']['App']['GetSystemLogs']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function ParseMetadata(arg1) {
  return window['go']['main']['App']['ParseMetadata'](arg1);
}

export function RunOptimization(arg1) {
  return window['go']['main']['App']['RunOptimization'](arg1);
}

export function SaveGearset(arg1, arg2) {
  return window['go']['main']['App']['SaveGearset'](arg1, arg2);
}

export function UpdateExternalSources() {
  return window['go']['main']['App']['UpdateExternalSources']();
}
