// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function GetAvailableAugments(arg1:string,arg2:number,arg3:string):Promise<Array<models.XMLAugment>>;

export function GetAvailableFiligrees(arg1:string):Promise<Array<models.XMLFiligree>>;

export function GetAvailableItems(arg1:string,arg2:number,arg3:string):Promise<Array<models.XMLItem>>;

export function GetItemDetails(arg1:string):Promise<models.XMLItem>;

export function GetSystemLogs():Promise<Array<string>>;

export function OpenFile(arg1:string):Promise<void>;

export function ParseMetadata(arg1:string):Promise<void>;

export function RunOptimization(arg1:main.OptimizationPayload):Promise<main.ResultPayload>;

export function UpdateExternalSources():Promise<string>;
