// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemLogs() {
  return window['go']['main']['App']['GetSystemLogs']();
}

export function ParseMetadata(arg1) {
  return window['go']['main']['App']['ParseMetadata'](arg1);
}

export function RunOptimization(arg1) {
  return window['go']['main']['App']['RunOptimization'](arg1);
}
