// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptAll(arg1) {
  return window['go']['main']['App']['AcceptAll'](arg1);
}

export function BuildIDForCurrentConfig(arg1) {
  return window['go']['main']['App']['BuildIDForCurrentConfig'](arg1);
}

export function DeleteBuild(arg1) {
  return window['go']['main']['App']['DeleteBuild'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAugmentByName(arg1) {
  return window['go']['main']['App']['GetAugmentByName'](arg1);
}

export function GetAvailableAugments(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAvailableAugments'](arg1, arg2, arg3);
}

export function GetAvailableFiligrees(arg1) {
  return window['go']['main']['App']['GetAvailableFiligrees'](arg1);
}

export function GetAvailableItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAvailableItems'](arg1, arg2, arg3);
}

export function GetFiligreeByName(arg1) {
  return window['go']['main']['App']['GetFiligreeByName'](arg1);
}

export function GetItemDetails(arg1) {
  return window['go']['main']['App']['GetItemDetails'](arg1);
}

export function GetSetBonus(arg1) {
  return window['go']['main']['App']['GetSetBonus'](arg1);
}

export function GetSlotAlternatives(arg1) {
  return window['go']['main']['App']['GetSlotAlternatives'](arg1);
}

export function GetStatSets() {
  return window['go']['main']['App']['GetStatSets']();
}

export function GetSuggestion(arg1) {
  return window['go']['main']['App']['GetSuggestion'](arg1);
}

export function GetSystemLogs() {
  return window['go']['main']['App']['GetSystemLogs']();
}

export function GetTroveOwnedItems(arg1) {
  return window['go']['main']['App']['GetTroveOwnedItems'](arg1);
}

export function ImportGearsetContent(arg1, arg2) {
  return window['go']['main']['App']['ImportGearsetContent'](arg1, arg2);
}

export function ImportGearsetFile(arg1) {
  return window['go']['main']['App']['ImportGearsetFile'](arg1);
}

export function ImportLegacyGearsets() {
  return window['go']['main']['App']['ImportLegacyGearsets']();
}

export function ListBuilds() {
  return window['go']['main']['App']['ListBuilds']();
}

export function LoadBuild(arg1) {
  return window['go']['main']['App']['LoadBuild'](arg1);
}

export function LoadTroveInventory(arg1) {
  return window['go']['main']['App']['LoadTroveInventory'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function ParseMetadata(arg1) {
  return window['go']['main']['App']['ParseMetadata'](arg1);
}

export function RunOptimization(arg1) {
  return window['go']['main']['App']['RunOptimization'](arg1);
}

export function SaveGearset(arg1, arg2) {
  return window['go']['main']['App']['SaveGearset'](arg1, arg2);
}

export function SearchItemsByStat(arg1, arg2) {
  return window['go']['main']['App']['SearchItemsByStat'](arg1, arg2);
}

export function VerifyGearsetChecksum(arg1) {
  return window['go']['main']['App']['VerifyGearsetChecksum'](arg1);
}
