// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function GetAppVersion():Promise<string>;

export function GetAugmentByName(arg1:string):Promise<models.XMLAugment>;

export function GetAvailableAugments(arg1:string,arg2:number,arg3:string):Promise<Array<models.XMLAugment>>;

export function GetAvailableFiligrees(arg1:string):Promise<Array<models.XMLFiligree>>;

export function GetAvailableItems(arg1:string,arg2:number,arg3:string):Promise<Array<models.XMLItem>>;

export function GetFiligreeByName(arg1:string):Promise<models.XMLFiligree>;

export function GetItemDetails(arg1:string):Promise<models.XMLItem>;

export function GetSetBonus(arg1:string):Promise<models.XMLSetBonus>;

export function GetSlotAlternatives(arg1:main.AlternativesPayload):Promise<main.AlternativesResult>;

export function GetStatSets():Promise<main.StatSetsFile>;

export function GetSystemLogs():Promise<Array<string>>;

export function GetTroveOwnedItems(arg1:string):Promise<main.TroveOwnedItemsResult>;

export function LoadTroveInventory(arg1:string):Promise<main.TroveInventoryResult>;

export function OpenFile(arg1:string):Promise<void>;

export function ParseMetadata(arg1:string):Promise<void>;

export function RunOptimization(arg1:main.OptimizationPayload):Promise<main.ResultPayload>;

export function SaveGearset(arg1:main.OptimizationPayload,arg2:main.ResultPayload):Promise<string>;

export function SearchItemsByStat(arg1:string,arg2:number):Promise<main.StatSearchResult>;

export function VerifyGearsetChecksum(arg1:string):Promise<main.GearsetChecksumResult>;
