// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSystemLogs():Promise<Array<string>>;

export function ParseMetadata(arg1:string):Promise<void>;

export function RunOptimization(arg1:main.OptimizationPayload):Promise<main.ResultPayload>;
